# Use this in your UnturnedImages/config.yaml file
- Id: "38500-38514;38600-38611;39500-39503" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/1759818554/items/{ItemId}.png" # The repository of the override.