# Use this in your UnturnedImages/config.yaml file
- Id: "5002050020;50030-50031;50040-50041;5005050050;5006050060;50070-50071" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/2658860724/items/{ItemId}.png" # The repository of the override.