# Use this in your UnturnedImages/config.yaml file
- Id: "16000-16001" # The ID of the override.
  Repository: "https://cdn.jsdelivr.net/gh/SilKsPlugins/UnturnedIcons@images/modded/3139585868/items/{ItemId}.png" # The repository of the override.